# Generated by Django 6.0 on 2025-12-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='hours',
            field=models.FloatField(default=0.0),
        ),
    ]
